version: "3.8"

services:
  # --- 1. Bash Monitoring Service ---
  bash-service:
    build:
      context: .
      dockerfile: Dockerfile.bash

    container_name: system-monitor-bash

    restart: always

  # --- 2. Python Monitoring Service ---
  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python

    container_name: system-monitor-python

    restart: always

networks:
  default:
    name: system_monitor_network
    driver: bridge
